using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._White.Contract.UI;

[GenerateTypedNameReferences]
public sealed partial class ContractorWindow : DefaultWindow
{
    private readonly ContractorBoundUserInterface _owner;
    public ContractorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }
}
