#Wizard outfit startingGear definitions.
- type: startingGear
  id: WizardBlueGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorDarkBlue
    head: ClothingHeadHatWizard
    outerClothing: ClothingOuterWizard
    shoes: ClothingShoesWizard
    id: PassengerPDA
    ears: ClothingHeadsetService
  storage:
    back:
    - BoxSurvival

- type: startingGear
  id: WizardRedGear
  parent: WizardBlueGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorRed
    head: ClothingHeadHatRedwizard
    outerClothing: ClothingOuterWizardRed
    shoes: ClothingShoesWizard
    id: PassengerPDA
    ears: ClothingHeadsetService

- type: startingGear
  id: WizardVioletGear
  parent: WizardBlueGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorPurple
    head: ClothingHeadHatVioletwizard
    outerClothing: ClothingOuterWizardViolet
    shoes: ClothingShoesWizard
    id: PassengerPDA
    ears: ClothingHeadsetService

- type: startingGear
  id: WizardHardsuitGear
  parent: WizardVioletGear
  equipment:
    outerClothing: ClothingOuterHardsuitWizard
    shoes: ClothingShoesWizard
    id: PassengerPDA
    ears: ClothingHeadsetService
