# Jumpsuit
- type: itemLoadout
  id: HeadofSecurityJumpsuit
  equipment: HeadofSecurityJumpsuit

- type: startingGear
  id: HeadofSecurityJumpsuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoS

- type: itemLoadout
  id: HeadofSecurityJumpskirt
  equipment: HeadofSecurityJumpskirt

- type: startingGear
  id: HeadofSecurityJumpskirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoS

- type: itemLoadout
  id: HeadofSecurityTurtleneck
  equipment: HeadofSecurityTurtleneck

- type: startingGear
  id: HeadofSecurityTurtleneck
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSAlt

- type: itemLoadout
  id: HeadofSecurityTurtleneckSkirt
  equipment: HeadofSecurityTurtleneckSkirt

- type: startingGear
  id: HeadofSecurityTurtleneckSkirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoSAlt

- type: itemLoadout
  id: HeadofSecurityFormalSuit
  equipment: HeadofSecurityFormalSuit

- type: startingGear
  id: HeadofSecurityFormalSuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitHosFormal

- type: itemLoadout
  id: HeadofSecurityFormalSkirt
  equipment: HeadofSecurityFormalSkirt

- type: startingGear
  id: HeadofSecurityFormalSkirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHosFormal

- type: itemLoadout # WD
  id: HeadofSecurityJumpsuitHoSGrey
  equipment: HeadofSecurityJumpsuitHoSGrey
- type: startingGear
  id: HeadofSecurityJumpsuitHoSGrey
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSGrey

- type: itemLoadout # WD
  id: HeadofSecurityJumpsuitHoSBlue
  equipment: HeadofSecurityJumpsuitHoSBlue
- type: startingGear
  id: HeadofSecurityJumpsuitHoSBlue
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSBlue

# Head
- type: itemLoadout
  id: HeadofSecurityHead
  equipment: HeadofSecurityHead

- type: startingGear
  id: HeadofSecurityHead
  equipment:
    head: ClothingHeadHatHoshat

- type: itemLoadout
  id: HeadofSecurityBeret
  equipment: HeadofSecurityBeret

- type: startingGear
  id: HeadofSecurityBeret
  equipment:
    head: ClothingHeadHatBeretHoS

# Neck
- type: itemLoadout
  id: HeadofSecurityCloak
  equipment: HeadofSecurityCloak

- type: startingGear
  id: HeadofSecurityCloak
  equipment:
    neck: ClothingNeckCloakHos

- type: itemLoadout
  id: HeadofSecurityMantle
  equipment: HeadofSecurityMantle

- type: startingGear
  id: HeadofSecurityMantle
  equipment:
    neck: ClothingNeckMantleHOS

# OuterClothing - removed
- type: itemLoadout
  id: HeadofSecurityCoat
  equipment: HeadofSecurityCoat

- type: startingGear
  id: HeadofSecurityCoat
  equipment:
    outerClothing: ClothingOuterCoatHoSTrench

- type: itemLoadout
  id: HeadofSecurityWinterCoat
  equipment: HeadofSecurityWinterCoat

- type: startingGear
  id: HeadofSecurityWinterCoat
  equipment:
    outerClothing: ClothingOuterWinterHoS

# PDA

- type: itemLoadout # WD
  id: HeadofSecurityPDA
  equipment: HeadofSecurityPDA
- type: startingGear
  id: HeadofSecurityPDA
  equipment:
    id: HoSPDA

# Underwear
- type: itemLoadout # WD
  id: HeadofSecurityBoxer
  equipment: HeadofSecurityBoxer
- type: startingGear
  id: HeadofSecurityBoxer
  equipment:
    underwearb: ClothingUnderwearBottomBoxersHOS

- type: itemLoadout # WD
  id: HeadofSecurityPanties
  equipment: HeadofSecurityPanties
- type: startingGear
  id: HeadofSecurityPanties
  equipment:
    underwearb: ClothingUnderwearBottomPantiesHOS

- type: itemLoadout # WD
  id: HeadofSecurityBra
  equipment: HeadofSecurityBra
- type: startingGear
  id: HeadofSecurityBra
  equipment:
    underweart: ClothingUnderwearTopBraHOS

# Socks
- type: itemLoadout # WD
  id: Socks1White
  equipment: Socks1White
- type: startingGear
  id: Socks1White
  equipment:
    socks: ClothingUnderwearSocksNormal

- type: itemLoadout # WD
  id: Socks2White
  equipment: Socks2White
- type: startingGear
  id: Socks2White
  equipment:
    socks: ClothingUnderwearSocksHigh

- type: itemLoadout # WD
  id: Socks3White
  equipment: Socks3White
- type: startingGear
  id: Socks3White
  equipment:
    socks: ClothingUnderwearSocksThigh

- type: itemLoadout # WD
  id: Socks4White
  equipment: Socks4White
- type: startingGear
  id: Socks4White
  equipment:
    socks: ClothingUnderwearSocksGarter

- type: itemLoadout # WD
  id: Socks1Black
  equipment: Socks1Black
- type: startingGear
  id: Socks1Black
  equipment:
    socks: ClothingUnderwearSocksThinKnee

- type: itemLoadout # WD
  id: Socks2Black
  equipment: Socks2Black
- type: startingGear
  id: Socks2Black
  equipment:
    socks: ClothingUnderwearSocksThinThigh

- type: itemLoadout # WD
  id: Socks3Black
  equipment: Socks3Black
- type: startingGear
  id: Socks3Black
  equipment:
    socks: ClothingUnderwearSocksPantyhose

- type: itemLoadout # WD
  id: Socks1BlackWhite
  equipment: Socks1BlackWhite
- type: startingGear
  id: Socks1BlackWhite
  equipment:
    socks: ClothingUnderwearSocksStripedKnee

- type: itemLoadout # WD
  id: Socks2BlackWhite
  equipment: Socks2BlackWhite
- type: startingGear
  id: Socks2BlackWhite
  equipment:
    socks: ClothingUnderwearSocksStripedThigh

#Striped stockings
- type: itemLoadout # WD
  id: Socks1Bee
  equipment: Socks1Bee
- type: startingGear
  id: Socks1Bee
  equipment:
    socks: ClothingUnderwearSocksBeeKnee

- type: itemLoadout # WD
  id: Socks2Bee
  equipment: Socks2Bee
- type: startingGear
  id: Socks2Bee
  equipment:
    socks: ClothingUnderwearSocksBeeThigh

- type: itemLoadout # WD
  id: Stockings1LightPink
  equipment: Stockings1LightPink
- type: startingGear
  id: Stockings1LightPink
  equipment:
    socks: ClothingUnderwearStockingsLightPink

- type: itemLoadout # WD
  id: Stockings2Cyan
  equipment: Stockings2Cyan
- type: startingGear
  id: Stockings2Cyan
  equipment:
    socks: ClothingUnderwearStockingsCyan

- type: itemLoadout # WD
  id: Stockings3LightPurple
  equipment: Stockings3LightPurple
- type: startingGear
  id: Stockings3LightPurple
  equipment:
    socks: ClothingUnderwearStockingsLightPurple

- type: itemLoadout # WD
  id: Stockings4Green
  equipment: Stockings4Green
- type: startingGear
  id: Stockings4Green
  equipment:
    socks: ClothingUnderwearStockingsGreen

- type: itemLoadout # WD
  id: Stockings5Pink
  equipment: Stockings5Pink
- type: startingGear
  id: Stockings5Pink
  equipment:
    socks: ClothingUnderwearStockingsPink

- type: itemLoadout # WD
  id: Stockings6Orange
  equipment: Stockings6Orange
- type: startingGear
  id: Stockings6Orange
  equipment:
    socks: ClothingUnderwearStockingsLightOrange

- type: itemLoadout # WD
  id: Stockings7Blue
  equipment: Stockings7Blue
- type: startingGear
  id: Stockings7Blue
  equipment:
    socks: ClothingUnderwearStockingsBlue

- type: itemLoadout # WD
  id: Stockings8Yellow
  equipment: Stockings8Yellow
- type: startingGear
  id: Stockings8Yellow
  equipment:
    socks: ClothingUnderwearStockingsLightYellow
