- type: entity
  id: BaseStation
  abstract: true
  components:
    - type: StationData

- type: entity
  id: BaseRandomStation
  abstract: true
  components:
    - type: StationRandomTransform

- type: entity
  id: BaseStationCargo
  abstract: true
  components:
    - type: StationBankAccount
    - type: StationCargoOrderDatabase
    - type: StationCargoBountyDatabase

- type: entity
  id: BaseStationJobsSpawning
  abstract: true
  components:
    - type: StationJobs
      availableJobs: {}
    - type: StationSpawning

- type: entity
  id: BaseStationRecords
  abstract: true
  components:
    - type: StationRecords

- type: entity
  id: BaseStationArrivals
  abstract: true
  components:
    - type: StationArrivals

- type: entity
  id: BaseStationGateway
  abstract: true
  components:
    - type: GatewayGenerator

- type: entity
  id: BaseStationShuttles
  abstract: true
  components:
    - type: StationCargoShuttle
      path: /Maps/White/Shuttles/cargo.yml
    - type: GridSpawn
      groups:
#        trade:
#          addComponents:
#            - type: ProtectedGrid
#            - type: TradeStation
#          paths:
#            - /Maps/Shuttles/trading_outpost.yml
        # Spawn last
        ruins:
          hide: true
          nameGrid: true
          minCount: 43
          maxCount: 43
          stationGrid: false
          paths:
          - /Maps/Ruins/biodome_satellite.yml
          - /Maps/Ruins/derelict.yml
          - /Maps/Ruins/djstation.yml
          - /Maps/Ruins/old_ai_sat.yml
          - /Maps/Ruins/relaystation.yml
          - /Maps/Ruins/syndicate_dropship.yml
          - /Maps/Ruins/whiteship_ancient.yml
          - /Maps/Ruins/whiteship_bluespacejumper.yml
          - /Maps/Salvage/asteroid-base.yml
          - /Maps/Salvage/cargo-1.yml
          - /Maps/Salvage/engineering-chunk.yml
          - /Maps/Salvage/hauling-shuttle.yml
          - /Maps/Salvage/meatball.yml
          - /Maps/Salvage/medium-1.yml
          - /Maps/Salvage/medium-crashed-shuttle.yml
          - /Maps/Salvage/medium-dock.yml
          - /Maps/Salvage/medium-library.yml
          - /Maps/Salvage/medium-pet-hospital.yml
          - /Maps/Salvage/medium-pirate.yml
          - /Maps/Salvage/medium-ruined-emergency-shuttle.yml
          - /Maps/Salvage/medium-silent-orchestra.yml
          - /Maps/Salvage/medium-template.yml
          - /Maps/Salvage/medium-vault-1.yml
          - /Maps/Salvage/outpost-arm.yml
          - /Maps/Salvage/ruin-cargo-salvage.yml
          - /Maps/Salvage/security-chunk.yml
          - /Maps/Salvage/small-1.yml
          - /Maps/Salvage/small-2.yml
          - /Maps/Salvage/small-3.yml
          - /Maps/Salvage/small-4.yml
          - /Maps/Salvage/small-a-1.yml
          - /Maps/Salvage/small-ai-survey-drone.yml
          - /Maps/Salvage/small-cargo.yml
          - /Maps/Salvage/small-chapel.yml
          - /Maps/Salvage/small-chef.yml
          - /Maps/Salvage/small-party.yml
          - /Maps/Salvage/small-ship-1.yml
          - /Maps/Salvage/small-syndicate.yml
          - /Maps/Salvage/small-template.yml
          - /Maps/Salvage/small-tesla.yml
          - /Maps/Salvage/stationstation.yml
          - /Maps/Salvage/tick-colony.yml
          - /Maps/Salvage/vegan-meatball.yml
          - /Maps/Salvage/wh-salvage.yml
- type: entity
  id: BaseStationCentcomm
  abstract: true
  components:
    - type: StationCentcomm

- type: entity
  id: BaseStationEvacuation
  abstract: true
  components:
    - type: StationEmergencyShuttle

- type: entity
  id: BaseStationAlertLevels
  abstract: true
  components:
    - type: AlertLevel
      alertLevelPrototype: stationAlerts

- type: entity
  id: BaseStationExpeditions
  abstract: true
  components:
    - type: SalvageExpeditionData

- type: entity
  id: BaseStationMagnet
  abstract: true
  components:
    - type: SalvageMagnetData

- type: entity
  id: BaseStationSiliconLawCrewsimov
  abstract: true
  components:
  - type: SiliconLawProvider
    laws: Crewsimov

- type: entity
  id: BaseStationNews
  abstract: true
  components:
    - type: StationNews

- type: entity
  id: BaseStationAllEventsEligible
  abstract: true
  components:
    - type: StationEventEligible # For when someone makes this more granular in the future.

- type: entity
  id: BaseStationTeleportLocation
  abstract: true
  components:
    - type: TeleportLocationTargetStation
