using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Miracle.Changeling.UI.ListViewSelector;

[GenerateTypedNameReferences]
public partial class ListViewSelectorWindow : DefaultWindow
{
    public Action<string>? ItemSelected;

    private readonly IPrototypeManager _prototypeManager;
    public ListViewSelectorWindow(IPrototypeManager prototypeManager)
    {
        RobustXamlLoader.Load(this);
        _prototypeManager = prototypeManager;
    }

    public void PopulateList(Dictionary<string, string> items)
    {
        ItemsContainer.RemoveAllChildren();

        foreach (var item in items)
        {
            var button = new Button();
            var itemName = item;

            button.Text = item.Value;

            button.OnPressed += _ => ItemSelected?.Invoke(item.Key);

            ItemsContainer.AddChild(button);
        }
    }
}
