using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._White.Genetics;

[GenerateTypedNameReferences]
public sealed partial class DNAScannerWindow : Control
{
    public DNAScannerWindow()
    {
        RobustXamlLoader.Load(this);
    }
}

